str = 'Hello World'
new_str_1 = str.lower()
new_str_2 = str.upper()
print(str, new_str_1, new_str_2)
print(str.count('o'))
print(str.find('r'))
print(str.find('a'))
print(str.split(' ')[0])
print(str.startswith('H'))
print(str.endswith('P'))